repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: no-commit-to-branch

- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pytest -vvvv -l
    language: system
    pass_filenames: false
    verbose: true
