@startuml

title lscat and data

abstract class lscat.AbstractTracker <<(A, red)>>{
    - {abstract} orders
    - {abstract} generator
    +update()
    -_inspect()
}
class lscat.TrackDownloads {
    ..Implements..
    - orders
    - generator
}
class lscat.TrackDownloadsUser {
    ..Implements..
    - orders
    - generator
}

lscat.AbstractTracker <-- lscat.TrackDownloadsUser
lscat.AbstractTracker <-- lscat.TrackDownloads

ui.AbstractUsers .down.* lscat.TrackDownloadsUser
ui.AbstractGallery .down.* lscat.TrackDownloads


abstract class data.AbstractData <<(A, red)>>{
    ..Required methods..
    +{abstract}update()
    +{abstract}artist_user_id()
    ..Required properties..
    +{abstract} next_url
    +{abstract} all_urls
    +{abstract} all_names
    ..Common attributes..
    +main_path
    +offset
    +page_num
    +all_pages_cache
    ..Common methods..
    +download_path()
    +next_offset()
    +urls_as_names()
    +newnames_with_ext()
}
class data.GalleryData {
    ..Implements..
    +update()
    +artist_user_id()
    + next_url
    + all_urls
    + all_names
    ..Unique..
    + current_illusts
    +post_json()
    +image_id()
    +url()
}

class data.UserData {
    ..Implements..
    +update()
    +artist_user_id()
    + next_url
    + all_urls
    + all_names
    ..Unique..
    + names
    + profile_pic_urls
    + image_urls
    -iterate_cache()
    + splitpoint
}

class data.ImageData {
    + image_id
    + artist_illust_id
    + page_num
    + firstmode
    + page_urls
    + number_of_pages
    + download_path
    + current_url
    + next_img_url
    + image_filename
    + filepath
    + large_filename
}

data.GalleryData *-up- ui.AbstractGallery
data.ImageData <-up- ui.Image
data.UserData *-up- ui.AbstractUsers

data.GalleryData <-- data.AbstractData
data.UserData <-- data.AbstractData

@enduml
