@startuml

set namespaceSeparator none
skinparam linetype polyline

' Accessing attribute
skinparam object<<attr>>BackgroundColor GreenYellow
' Needs pixivrequest
skinparam object<<request>>BackgroundColor Gold
' In files module
skinparam object<<files>>BackgroundColor Bisque

title (Excludes access of self._data attribute)

object self.use_ueberzug <<attr>>
object self.scrollable <<attr>>
object self.tracker_class <<attr>>
object self.images <<attr>>
object self.max_images <<attr>>
object self.terminal_page <<attr>>
object self.is_gallery_mode <<attr>>
object self.prompt <<attr>>
object self.prefetch_thread <<attr>>

object print_page_info
object maybe_join_thread
object report
object scroll_or_show
object handle_scroll
object previous_page
object scroll_up
object scroll_down
object show_page
object remove_dir_if_exist <<files>>
object dir_not_empty <<files>>
object dir_up_to_date <<files>>

object pixivrequest <<request>>
object start <<request>>
object prefetch <<request>>
object prefetch_next_page <<request>>
object request_then_save <<request>>
object download_from_scratch <<request>>
object show_then_fetch <<request>>
object verify_up_to_date <<request>>
object download_save_images
object reload <<request>>
object next_page <<request>>

object handle_prompt <<request>>
'object help  ' Static method
object view_image
object back

report ---> print_page_info
report --> self.use_ueberzug

scroll_or_show ---> self.scrollable
scroll_or_show ---> handle_scroll
scroll_or_show ---> self.tracker_class

handle_scroll ---> self.images
handle_scroll ---> self.max_images
handle_scroll ---> self.terminal_page
handle_scroll ---> self.tracker_class

previous_page ---> self.terminal_page
previous_page ---> show_page


scroll_up ---> self.terminal_page
scroll_up ---> show_page

scroll_down ---> self.terminal_page
scroll_down ---> self.is_gallery_mode
scroll_down ---> show_page

show_page ---> dir_not_empty
show_page ---> scroll_or_show
show_page ---> report

dir_not_empty ---> dir_up_to_date


start ---> show_then_fetch
start ---> download_from_scratch
start ---> prefetch

prefetch ---> prefetch_next_page
prefetch ---> self.prefetch_thread

prefetch_next_page ---> maybe_join_thread
prefetch_next_page ---> request_then_save

request_then_save ---> pixivrequest

download_from_scratch ---> remove_dir_if_exist
download_from_scratch ---> request_then_save
download_from_scratch ---> download_save_images
download_from_scratch ---> report

show_then_fetch ---> scroll_or_show
show_then_fetch ---> request_then_save
show_then_fetch ---> verify_up_to_date
show_then_fetch ---> report

verify_up_to_date ---> dir_not_empty
verify_up_to_date ---> remove_dir_if_exist
verify_up_to_date ---> download_save_images

download_save_images ---> self.tracker_class
download_save_images ---> self.images

reload --> self.images
reload --> self.prompt
reload --> start

next_page ---> self.terminal_page
next_page ---> self.prefetch_thread
next_page ---> show_page
next_page ---> prefetch


handle_prompt --> self.images
handle_prompt --> reload

view_image ---> self.images
' view_image ----> back

back ---> scroll_or_show
back ---> report


' Other modes
object go_artist_gallery_coords
object go_artist_gallery_num
object go_artist_mode

go_artist_gallery_coords --> go_artist_gallery_num
go_artist_gallery_num ---> self.images
' go_artist_gallery_num ---> back

go_artist_mode ---> self.images
'go_artist_mode ---> show_page

@enduml
