@startuml

class SetupMixin {
    + start()
    + dir_exists()
    + remove_dir_if_exist()
    + request()
    + download_from_scratch()
    + show_then_fetch()
    + verify_up_to_date()
    ..HAS-A..
    + request
}

class UIMixin {
    -prefetch_thread
    + request_then_save()
    - prefetch_next_page()
    + next_page()
    + previous_page()
    + scroll_up()
    + scroll_down()
    - show_page()
    + download_save_images()
    + reload()
    + report()
    + dir_not_empty()
    - dir_up_to_date()
    ..HAS-A..
    + request
}

abstract class AbstractCommonMixin {
    -max_images
    -tracker_class
    +offset
    +images
    +terminal_page
    +use_ueberzug
    +scrollable
    + scroll_or_show()
    + handle_scroll()
    + maybe_join_thread()
    +{abstract} print_page_info()
}

class GalleryCommonMixin {
    ..Implements..
    -max_images
    -tracker_class
    -is_gallery_mode
    + print_page_info()
    ..New..
    + back()
    + view_image()
}

SetupMixin -left[hidden]-> AbstractCommonMixin
UIMixin -left[hidden]-> AbstractCommonMixin

GalleryUI --|> UIMixin
GallerySetup --|> SetupMixin

GalleryCommonMixin --|> AbstractCommonMixin
GallerySetup --|> GalleryCommonMixin
GalleryUI --|> GalleryCommonMixin

class ArtistGallery {
    + ui
    + setup
    + handle_prompt()
    + help()
    + pixivrequest()
}
ArtistGallery -up-|> GalleryData
ArtistGallery *-- GallerySetup: composes setup
ArtistGallery *-- GalleryUI: composes ui



class IllustFollowGallery {
    + ui
    + setup
    + handle_prompt()
    + help()
    + pixivrequest()
}

IllustFollowGallery -up-|> GalleryData
IllustFollowGallery *-- GalleryUI
IllustFollowGallery *-- GallerySetup



IllustRecommendedGallery -up-|> ArtistGallery
class IllustRecommendedGallery {
    ..Overrides..
    + pixivrequest()
}



class UsersCommonMixin {
    ..Implements..
    -max_images
    -tracker_class
    -is_gallery_mode
    + print_page_info()
    ..New..
    + go_artist_mode()
}

UsersCommonMixin --|> AbstractCommonMixin
UsersSetup --|> SetupMixin
UsersSetup --|> UsersCommonMixin
UsersUI --|> UIMixin
UsersUI --|> UsersCommonMixin

class FollowingUsers {
    + ui
    + setup
    + pixivrequest()
}

FollowingUsers -up-|> UserData
FollowingUsers *-- UsersSetup
FollowingUsers *-- UsersUI

note right of FollowingUsers
    This class adds self.pixivrequest() to self.ui and self.setup
    as self.ui.request and self.setup.request respectively
end note


@enduml




abstract class CommonMixin {
    -max_images
    -tracker_class
    +offset
    +images
    +terminal_page
    +use_ueberzug
    +scrollable
    + scroll_or_show()
    + handle_scroll()
    + maybe_join_thread()
    +{abstract} pixivrequest()
    +{abstract} print_page_info()
}

class SetupMixin {
    + start()
    + dir_exists()
    + remove_dir_if_exist()
    + request()
    + download_from_scratch()
    + show_then_fetch()
    + verify_up_to_date()
}

class UIMixin {
    -prefetch_thread
    + request_then_save()
    - prefetch_next_page()
    + next_page()
    + previous_page()
    + scroll_up()
    + scroll_down()
    - show_page()
    + download_save_images()
    + reload()
    + report()
    + dir_not_empty()
    - dir_up_to_date()
}

SetupMixin -right[hidden]-> CommonMixin
UIMixin -left[hidden]-> CommonMixin


abstract class AbstractGalleryCommon {
    -max_images
    -tracker_class
    -is_gallery_mode
    + print_page_info()
}


class ArtistGalleryCommon {
    + pixivrequest()
}

class SetupArtistGallery {
    +artist_user_id
    +main_path
    +download_path
}

class ArtistGallery {
    + new()
    + view_image()
    + back()
    + handle_prompt()
    + help()
}
note right of ArtistGallery
    back() has to be shared with IllustFollow mode, but it can't be moved anywhere
    Not to ArtistGalleryCommon, because pixivrequest is unique to mode 1
    Not to AbstractGalleryCommon, because now setup has something it doesn't need
    Use composition for common. UI object and Setup object HAS-A pixivrequest,
    but only Gallery objects HAS-A back method
end note

AbstractGalleryCommon --|> CommonMixin
ArtistGalleryCommon --|> AbstractGalleryCommon
IllustFollowGalleryCommon --|> AbstractGalleryCommon

SetupArtistGallery --|> ArtistGalleryCommon
SetupArtistGallery ----|> SetupMixin
ArtistGallery --up-|> GalleryData
ArtistGallery ---|> ArtistGalleryCommon
ArtistGallery ----|> UIMixin

