@startuml
title AbstractUI (modes 1, 3, 4, 5)

actor User

== Mode selection ==
User -> ui ++: Mode selection
ui --> User: Ask for user id (mode 1 only)
User --> ui: Pixiv id
database data
create data
ui -> data: main_path
ui -> api ++: JSON request
return JSON response
ui -> data: Stores response
create lscat
ui -> lscat: Add tracker
ui -> download: Download images
activate download
download -> lscat ++: Image 2 done
download -> lscat: Image 1 done
lscat -> User: Display image 1
lscat -> User: Display image 2
download -> lscat: Image 3 done
deactivate download
lscat -> User: Display image 3
deactivate lscat
ui --> User: Print info
group prefetching
    ui -> api ++: JSON request
    return JSON response
    ui -> data: Stores response
    ui -> download: Download page
    activate download
    deactivate download
end
return Prompt
|||

== Next page ==
User -> ui ++: Next Page
ui --> User: Displays images, prints info
ui -> ui: prefetching
return
|||

== Previous page ==
User -> ui ++: previous_page()
return Displays images, prints info
|||

== Reload ==
User -> ui ++: reload()
ui -> User: Are you sure?
User -> ui: Confirmation
ui -> data: Clear all_pages_cache
return Restarts mode
|||

== Open image ==
User -> ui ++: Open image
ui -> data ++: image_id
return image_id
return Opened {link}!
|||

== Download image ==
User -> ui ++: Download image
ui -> data ++: url
return url
ui -> download: download_image_verified()
activate download
deactivate download
return
|||
@enduml


