@startuml
title Gallery modes (mode 1 and 5)

actor User

== View image (go to image mode) ==
User -> ui ++: View image
ui -> gdata ++: post_json
return post_json
database idata
create idata
ui -> idata: Stores post_json
ui -> User: Displays image
ui -> download ++: Download image(s)
return
return image_prompt()
|||


== Go artist mode (mode 5 only) ==
User -> ui ++: go_artist_mode()
ui -> gdata ++: artist_user_id
return artist_user_id
return ArtistGallery
|||

@enduml


