@startuml

title koneko

abstract class main.AbstractLoop <<(A, red)>>{
  +start()
  -{abstract}_prompt_url_or_id()
  -_process_url_or_input()
  -_validate_input()
  -{abstract}_go_to_mode()
}

class main.ArtistModeLoop {
}
package main {
    object illust_follow_mode_loop
}

main.AbstractLoop <-up- main.ArtistModeLoop
main.AbstractLoop <-up[hidden]- illust_follow_mode_loop

abstract class ui.AbstractUI <<(A, red)>>{
    ..Required attributes..
    - {abstract} data
    - {abstract} download_function
    --
    -{abstract}data_class()
    -{abstract}tracker()
    -{abstract}show_instant()
    -{abstract}pixivrequest()
    -{abstract}action_before_prefetch()
    -{abstract}print_page_info()
    ..Behaviour..
    +start()
    +next_page()
    +preview_page()
    +reload()
}

abstract class ui.AbstractGallery <<(A, red)>>{
    +view_image()
    -_back()
    +{abstract}handle_prompt()
    +{abstract}{static}help()
}
ui.AbstractUI <|-up- ui.AbstractGallery

class ui.ArtistGallery <<(C, cyan)>>{
    - _artist_user_id
    -_pixivrequest()
}
class ui.IllustFollowGallery <<(C, cyan)>>{
    -_pixivrequest()
    +go_artist_gallery_coords()
    +go_artist_gallery_num()
}
main.ArtistModeLoop*-down- ui.ArtistGallery

illust_follow_mode_loop*-down- ui.IllustFollowGallery

ui.AbstractGallery <-down- ui.IllustFollowGallery

ui.AbstractGallery <-down- ui.ArtistGallery

class main.ViewPostModeLoop {
    -_process_url_or_input()
}
package ui {
    object view_post_mode
    object display_image
}
class ui.Image <<(C, cyan)>>{
    + download_image()
    + open_image()
    + next_image()
    + previous_image()
    + show_full_res()
    + jump_to_page()
    + leave()
}

main.AbstractLoop <-up- main.ViewPostModeLoop
main.ViewPostModeLoop ..> view_post_mode
view_post_mode ..> ui.Image
display_image ..> ui.Image
display_image <.. ui.AbstractGallery


class main.FollowingUsersModeLoop {
    -_process_url_or_input()
    -_validate_input()
}
class main.SearchUsersModeLoop
main.AbstractLoop <-up- main.FollowingUsersModeLoop
main.AbstractLoop <-up- main.SearchUsersModeLoop

class ui.FollowingUsers <<(C, cyan)>> {
    - user
    -_pixivrequest()
}
class ui.SearchUsers <<(C, cyan)>> {
    - publicity
    - your_id
    -_pixivrequest()
}
abstract class ui.AbstractUsers <<(A, red)>>{
    +go_artist_mode()
}
ui.AbstractUI <|-up- ui.AbstractUsers
ui.AbstractUsers <-down- ui.FollowingUsers
ui.AbstractUsers <-down- ui.SearchUsers
main.FollowingUsersModeLoop*-down- ui.FollowingUsers
main.SearchUsersModeLoop*-down- ui.SearchUsers


abstract class lscat.AbstractTracker <<(A, red)>>{
    - {abstract} orders
    - {abstract} generator
    +update()
    -_inspect()
}
class lscat.TrackDownloads {
    - orders
    - generator
}
class lscat.TrackDownloadsUser {
    - orders
    - generator
}

lscat.AbstractTracker <- lscat.TrackDownloadsUser
lscat.AbstractTracker <-right- lscat.TrackDownloads

ui.AbstractUsers *.down. lscat.TrackDownloadsUser
ui.AbstractGallery *.left lscat.TrackDownloads

lscat.TrackDownloadsUser -up[hidden]-> lscat.TrackDownloads

package prompt {
    object user_prompt
    object gallery_prompt
    object image_prompt

    user_prompt -down[hidden]-> main.AbstractLoop
    gallery_prompt -down[hidden]-> main.AbstractLoop
    image_prompt -down[hidden]-> main.AbstractLoop

    main.ArtistModeLoop *-up-- gallery_prompt
    main.ViewPostModeLoop *-up-- image_prompt
    main.FollowingUsersModeLoop *-left-- user_prompt
    main.SearchUsersModeLoop *-left-- user_prompt
    illust_follow_mode_loop *-up-- gallery_prompt
}


class data.GalleryJson {
    + page_num
    + main_path
    + all_pages_cache
    + offset
    + current_illusts
    + next_url
    + download_path
    + first_img
    +update()
    +post_json()
    +artist_user_id()
    +image_id()
    +url()
}
class data.ImageJson {
    + image_id
    + artist_illust_id
    + page_num
    + page_urls
    + number_of_pages
    + download_path
    + image_filename
    + filepath
    + next_img_url
    + current_url
}
class data.UserJson {
    + page_num
    + main_path
    + offset
    + ids_cache
    + names_cache
    + download_path
    + all_urls
    + names
    + all_names
    + splitpoint
    + first_img
    + next_url
    + profile_pic_urls
    + image_urls
    +update()
    +artist_user_id()
}

data.GalleryJson *-up-- ui.AbstractGallery
data.ImageJson *-up-- ui.Image
data.UserJson *-up-- ui.AbstractUsers


class api.APIHandler << (S,#FF7700) Singleton >> {
    ..Initial login..
    + api
    - api_queue
    - api_thread
    + credentials
    +start()
    +await_login()
    ..Requests..
    +artist_gallery()
    +protected_illust_detail()
    +following_user_request()
    +search_user_request()
    +illust_follow_request()
    +protected_download()
}

api.APIHandler ---left[hidden]-> ui.AbstractUI

@enduml
