For planning purposes
Need to figure out how to cancel running threads

@startuml

title Multi-image previews (mode 2)

actor User

User -> ui ++: Mode 2
...
ui -> User:Displays image, prints info
ui -> User: Prompt
== No interrupt ==
create lscat
ui -> lscat
ui --> download ++:Download next 3 images
download --> lscat ++: Image 2 done
download --> lscat: Image 1 done
lscat -> User: Display image 1
lscat -> User: Display image 2
download --> lscat: Image 3 done
lscat -> User: Display image 3
lscat --> ui
deactivate lscat
return
return
|||


== User interrupts ==
...
ui -> User: Prompt
activate ui
ui --> download ++: Download next 3 images
download --> lscat ++: Image 2 done
download --> lscat: Image 1 done
lscat -> User: Display image 1
lscat -> User: Display image 2
User -> ui: Interrupt
ui -x lscat: Cancel
deactivate lscat
ui -x download: Cancel
deactivate download
ui -> ui: Run user action
ui --> User
deactivate ui

@enduml
