# This workflow will install Python dependencies, run tests and lint with a single version of Python on Ubuntu and macOS
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - os: macos-latest
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --ignore=F821,F722,W391
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=F821,F722,W391
        # These errors should all occur inside string type annotations, ignore if so
        flake8 . --count --exit-zero --select=F821,F722 --show-source
    - name: Test with pytest
      run: |
        pytest testing/ -vvvv -l -s
    - name: Try launching the application
      run: |
        python testing/run.py
